= GrowlHandler for Monolog

**GrowlHandler** is a handler for Monolog
that send notifications to Growl on Mac OS X and Windows.


== Install

* via https://packagist.org/packages/bartlett/monolog-growlhandler/[packagist] the current source dev-master or the stable version 1.0.0

== Documentation

The documentation for GrowlHandler 1.0 is available
in http://php5.laurent-laville.org/growlhandler/manual/1.0/en/[English]
to read it online or download to read it later (multiple formats).

AsciiDoc source code are available on `docs` folder of the repository.

== Contribute

Contributions to source code and its documentation are always welcome.

As developper, I'm always happy when I have the more informations as possible to check and find out issues.
This is the reason why I've created a https://github.com/llaville/phpunit-LoggerTestListener[PHPUnit TestSuite Listener for compatible PSR-3 Loggers].

And recently, for the php-compatinfo project, I've wrote a new PHPUnit ResultPrinter class, that is based on PSR-3 logger concept.
You can learn more on this http://php5.laurent-laville.org/compatinfo/blog/201505-PHPUnit-ResultPrinter.html[post]
in the CompatInfo's blog.

If you want to use it, then :

- install all the components via Composer

[source,bash]
----
$ php composer.phar require --dev bartlett/monolog-growlhandler
----

- create a `phpunit.xml` file with at least following contents :

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<phpunit
    backupGlobals="true"
    backupStaticAttributes="false"
    bootstrap="tests/bootstrap.dev.php"
    colors="true"
    stopOnError="false"
    stopOnFailure="false"
    stopOnIncomplete="false"
    stopOnRisky="false"
    stopOnSkipped="false"
    verbose="true"
    printerClass="Bartlett\Tests\Monolog\Handler\ResultPrinter"
>
    <filter>
        <whitelist>
            <directory suffix=".php">src/</directory>
        </whitelist>
    </filter>
    <testsuites>
        <testsuite name="Monolog GrowlHandler Test Suite">
            <directory suffix="Test.php">tests/</directory>
        </testsuite>
    </testsuites>
</phpunit>
----

- configure the PSR-3 logger in `tests\MonologConsoleLogger.php`, if you want to change some behaviors.

NOTE: Default will log all PHPUnit events in local file `phpunit-growlhandler-php<PHP_VERSION_ID>.log`
and log events corresponding to PHPUnit mode (`--verbose`, `--debug`) to the console.

.Output look like
----
PHPUnit 4.6.6 by Sebastian Bergmann and contributors.

Configuration read from C:\home\github\monolog-growlhandler\phpunit.xml

Monolog GrowlHandler Test Suite:

    Test suite started with 19 tests

Bartlett\Tests\Monolog\Handler\GrowlHandlerTest:

    Test suite started with 19 tests

Bartlett\Tests\Monolog\Handler\GrowlHandlerTest::testIsHandling:

    Test suite started with 8 tests

Bartlett\Tests\Monolog\Handler\GrowlHandlerTest::testIsHandling:

    Test suite ended. Results OK. Tests: 8, Assertions: 8

Bartlett\Tests\Monolog\Handler\GrowlHandlerTest::testIsHandlingLevel:

    Test suite started with 8 tests

Bartlett\Tests\Monolog\Handler\GrowlHandlerTest::testIsHandlingLevel:

    Test suite ended. Results OK. Tests: 8, Assertions: 8

Bartlett\Tests\Monolog\Handler\GrowlHandlerTest:

    Test suite ended. Results OK. Tests: 0, Assertions: 0

Monolog GrowlHandler Test Suite:

    Test suite ended. Results OK. Tests: 19, Assertions: 18

Time: 431 ms, Memory: 9.00Mb

Results OK. Tests: 19, Assertions: 18
----
